export const ADD_FRIEND = "ADD_FRIEND";
export const DELETE_FRIEND = "DELETE_FRIEND";
export const CHANGE_FAVOURITE_LIST = "CHANGE_FAVOURITE_LIST";
export const CHANGE_GENDER = "CHANGE_GENDER";
export const CHANGE_PAGINATION = "CHANGE_PAGINATION";
